#include "openfhe_dtm/EncryptedDem.hpp"
#include <algorithm>
#include <complex>
#include <regex>
#include <set>
#include <stdexcept>
namespace openfhe_dtm {
EncryptedDemStore::EncryptedDemStore(const IDtmProvider& d,const IHeBackend& h,std::filesystem::path p,bool c):dtm_(d),he_(h),directory_(std::move(p)),compress_(c){if(he_.slotCount()<kDemPackSlots)throw std::invalid_argument("packed DEM requires 32768 slots");std::filesystem::create_directories(directory_);}
bool EncryptedDemStore::stitchHasData(int x,int y)const{if(x<0||y<0)return false;if(auto*r=dynamic_cast<const RasterDtmProvider*>(&dtm_))return std::size_t(x)*64<r->widthCells()&&std::size_t(y)*64<r->heightCells();for(int j=0;j<2;++j)for(int i=0;i<2;++i){auto t=dtm_.loadTile(x+i,y+j);if(std::any_of(t.elevations_m.begin(),t.elevations_m.end(),[&](double z){return z!=dtm_.metadata().nodata;}))return true;}return false;}
std::pair<std::size_t,std::size_t> EncryptedDemStore::validShape(int x,int y)const{if(auto*r=dynamic_cast<const RasterDtmProvider*>(&dtm_)){auto sx=std::size_t(std::max(0,x))*64,sy=std::size_t(std::max(0,y))*64;return{sx<r->widthCells()?std::min<std::size_t>(128,r->widthCells()-sx):0,sy<r->heightCells()?std::min<std::size_t>(128,r->heightCells()-sy):0};}return{128,128};}
std::vector<double> EncryptedDemStore::stitchValues(int x0,int y0)const{std::vector<double>o(16384);if(!stitchHasData(x0,y0))return o;for(int ty=0;ty<2;++ty)for(int tx=0;tx<2;++tx){auto t=dtm_.loadTile(x0+tx,y0+ty);for(std::size_t y=0;y<64;++y)for(std::size_t x=0;x<64;++x){double z=t.elevations_m[y*t.width+x];if(z!=dtm_.metadata().nodata)o[(std::size_t(ty)*64+y)*128+std::size_t(tx)*64+x]=z/kDemScale;}}return o;}
std::filesystem::path EncryptedDemStore::packPath(int l,int x,int y,int m)const{if(compress_)return directory_/("pack16_"+std::to_string(l)+"_"+std::to_string(pack16BaseX0(x))+"_"+std::to_string(pack16BaseY0(y))+"_p"+std::to_string(m)+".ct");return directory_/("pack_"+std::to_string(l)+"_"+std::to_string(packLeftX0(x))+"_"+std::to_string(y)+"_p"+std::to_string(m)+".ct");}
std::filesystem::path EncryptedDemStore::findPack(int l,int x,int y,int*m)const{for(int n=1;n<=(compress_?15:3);++n){auto p=packPath(l,x,y,n);if(std::filesystem::exists(p)){if(m)*m=n;return p;}}return{};}
CipherVector EncryptedDemStore::createPack(int,int x,int y,int*m)const{if(!compress_){int b=packLeftX0(x);bool a=stitchHasData(b,y),c=stitchHasData(b+2,y);*m=(a?1:0)|(c?2:0);std::vector<double>p(32768);if(a){auto v=stitchValues(b,y);std::copy(v.begin(),v.end(),p.begin());}if(c){auto v=stitchValues(b+2,y);std::copy(v.begin(),v.end(),p.begin()+16384);}return he_.encrypt(he_.encode(p));}int bx=pack16BaseX0(x),by=pack16BaseY0(y);std::vector<std::complex<double>>p(32768);*m=0;for(int iy=0;iy<2;++iy)for(int ix=0;ix<2;++ix){int sx=bx+2*ix,sy=by+2*iy;if(!stitchHasData(sx,sy))continue;*m|=1<<pack16StitchBit(sx,sy);auto v=stitchValues(sx,sy);std::size_t off=ix?16384:0;for(std::size_t k=0;k<16384;++k)if(iy)p[off+k].imag(v[k]);else p[off+k].real(v[k]);}return he_.encrypt(he_.encodeComplex(p));}
std::pair<CipherVector,CipherVector> EncryptedDemStore::splitPack16(const CipherVector&p)const{auto c=he_.conjugate(p);return{he_.mulScalar(he_.add(p,c),{.5,0}),he_.mulScalar(he_.sub(p,c),{0,-.5})};}
EncryptedDemStitch EncryptedDemStore::loadOrEncrypt(int l,int x,int y){if(!stitchHasData(x,y))throw std::invalid_argument("requested stitch has no DEM");int m=0;auto p=findPack(l,x,y,&m);if(p.empty()){auto c=createPack(l,x,y,&m);p=packPath(l,x,y,m);he_.saveCipher(c,p);}return load(l,x,y);}
std::optional<EncryptedDemStitch> EncryptedDemStore::tryLoad(int l,int x,int y)const{int m=0;auto p=findPack(l,x,y,&m);if(p.empty())return{};int bit=compress_?pack16StitchBit(x,y):packStitchBit(x);if(!((m>>bit)&1))return{};CipherVector c;if(!compress_)c=he_.loadCipher(p);else{SplitKey k{l,pack16BaseX0(x),pack16BaseY0(y)};auto it=split_cache_.find(k);if(it==split_cache_.end())it=split_cache_.emplace(k,splitPack16(he_.loadCipher(p))).first;c=packImagChannel(y)?it->second.second:it->second.first;}auto[w,h]=validShape(x,y);return EncryptedDemStitch{l,x,y,std::size_t(packSlotOffset(x)),w,h,std::move(c)};}
EncryptedDemStitch EncryptedDemStore::load(int l,int x,int y)const{auto r=tryLoad(l,x,y);if(!r)throw std::runtime_error("stitch absent or population bit clear");return std::move(*r);}bool EncryptedDemStore::has(int l,int x,int y)const{int m=0;if(findPack(l,x,y,&m).empty())return false;int b=compress_?pack16StitchBit(x,y):packStitchBit(x);return(m>>b)&1;}
std::vector<StitchAddress> EncryptedDemStore::list(int level)const{std::vector<StitchAddress>o;std::regex re(compress_?R"(^pack16_(-?\d+)_(-?\d+)_(-?\d+)_p(\d+)\.ct$)":R"(^pack_(-?\d+)_(-?\d+)_(-?\d+)_p(\d+)\.ct$)");for(auto&e:std::filesystem::directory_iterator(directory_)){std::smatch m;auto n=e.path().filename().string();if(!e.is_regular_file()||!std::regex_match(n,m,re))continue;int l=std::stoi(m[1]),bx=std::stoi(m[2]),by=std::stoi(m[3]),mask=std::stoi(m[4]);if(level>=0&&l!=level)continue;for(int k=0;k<(compress_?4:2);++k){int x=bx+((k&1)?2:0),y=by+((k&2)?2:0),b=compress_?pack16StitchBit(x,y):packStitchBit(x);if((mask>>b)&1)o.push_back({l,x,y});}}return o;}
LevelEncryptStats EncryptedDemStore::encryptLevel(int l){auto*r=dynamic_cast<const RasterDtmProvider*>(&dtm_);if(!r)throw std::logic_error("level enumeration requires raster");int nx=int((r->widthCells()+127)/128),ny=int((r->heightCells()+127)/128);std::set<std::pair<int,int>>b;for(int y=0;y<ny;++y)for(int x=0;x<nx;++x){int sx=2*x,sy=2*y;b.insert(compress_?std::pair{pack16BaseX0(sx),pack16BaseY0(sy)}:std::pair{packLeftX0(sx),sy});}LevelEncryptStats s;s.total=b.size();for(auto[x,y]:b)if(!findPack(l,x,y,nullptr).empty())++s.skipped;else{loadOrEncrypt(l,x,y);++s.encrypted;}return s;}
void EncryptedDemStore::clearCache()const{split_cache_.clear();}
}
